on:
  pull_request: ~
  push:
    branches:
      - "main"

name: Static analysis

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl json
          coverage: none

      - name: Download dependencies
        run: composer install --no-interaction --no-progress --optimize-autoloader

      - name: Run PHPStan
        run: vendor/bin/phpstan --no-progress --memory-limit=2G
